default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: FB-KADAI_development

test:
  <<: *default
  database: FB-KADAI_test

production:
  <<: *default
  database: FB-KADAI_production
  username: FB-KADAI
  password: <%= ENV['FB-KADAI_DATABASE_PASSWORD'] %>
